---

- include: deploy.yml

# ------
# ACTION == "UPGRADE"
# ------

- when: action == "upgrade"
  name: "ensure version dir"
  file:
    path: "~/apps/{{ app_name }}/releases/{{ app_version }}"
    state: "directory"

- when: action == "upgrade"
  name: "copy release tar to its release version folder"
  copy:
    src: "~/releases/{{ app_name }}.tar.gz"
    dest: "~/apps/{{ app_name }}/releases/{{ app_version }}/"

- when: action == "upgrade"
  name: "run app"
  command: bash -lc "PORT=3000 ~/apps/{{ app_name }}/bin/{{ app_name }} upgrade {{ app_version }}"

